name: Build site on schedule or main branch update

on:
#   push:
#     branches:
#       - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "*/15 * * * *" # UTCなので9時間プラス

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8" 
          architecture: x64
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install pandas
          pip install beautifulsoup4
          pip install requests

      - name: Get latest korea page # 韓国公式
        run: |
          python page_get.py 1
      - name: commit & push
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update"
            git push
          fi
